// Every spec's layer, declared once. `ui` specs drive a browser and run on few workers;
// `api` specs never launch one (request fixture, direct imports, Supabase clients) and run
// wide. playwright.config.ts builds its two projects from these lists, and
// tests/spec-layers.spec.ts fails if a spec is in neither, in both, or is `api` while
// asking for a browser fixture. A new spec is `api` unless its behaviour needs a browser.

export const UI_SPECS = [
  'agent-chat-panel.spec.ts',
  'agent-panel-examples.spec.ts',
  'agent-panel-step3-lock.spec.ts',
  'assets-tab.spec.ts',
  'camera-derivation.spec.ts',
  'credits-page.spec.ts',
  'dashboard-project-card.spec.ts',
  'export-ui.spec.ts',
  'image-prompts-footer-navigation.spec.ts',
  'image-prompts-frame.spec.ts',
  'image-prompts-page.spec.ts',
  'image-prompts-supplementary.spec.ts',
  'new-project-intake.spec.ts',
  'poll-visibility.spec.ts',
  'retry-partial-phase.spec.ts',
  'shot-deletion.spec.ts',
  'shot-editing.spec.ts',
  'step-indicator-navigation.spec.ts',
  'storyboard-editing.spec.ts',
  'storyboard-motion.spec.ts',
  'storyboard-music-ui.spec.ts',
  'storyboard-page.spec.ts',
  'storyboard-preview.spec.ts',
  'storyboard-rail.spec.ts',
  'storyboard-step.spec.ts',
  'storyboard-footer-navigation.spec.ts',
  'video-prompts-step.spec.ts',
  'storyboard-tooltip.spec.ts',
  'storyboard-voiceover-ui.spec.ts',
  'usage-page.spec.ts',
  'workbench-footer-navigation.spec.ts',
] as const

export const API_SPECS = [
  'advance-step.spec.ts',
  'agent-image-prompts.spec.ts',
  'auth-session.spec.ts',
  'agent-turn-estimate.spec.ts',
  'agent-turn-ledger.spec.ts',
  'agent-turn.spec.ts',
  'build-agent-messages.spec.ts',
  'claude-guard.spec.ts',
  'credit-figures-equivalence.spec.ts',
  'credit-ledger-schema.spec.ts',
  'credits-config.spec.ts',
  'derive-phase.spec.ts',
  'duration.spec.ts',
  'elements-read.spec.ts',
  'elements-reference-generation.spec.ts',
  'elements-reference.spec.ts',
  'elements-write.spec.ts',
  'enums-drift.spec.ts',
  'export-logic.spec.ts',
  'export-render.spec.ts',
  'export-worker-poll.spec.ts',
  'export-worker.spec.ts',
  'exports-route.spec.ts',
  'fixed-price-ledger.spec.ts',
  'format-clock-time.spec.ts',
  'generations-claim.spec.ts',
  'image-prompt-edit.spec.ts',
  'image-prompt-generation.spec.ts',
  'image-prompts-advance.spec.ts',
  'image-prompts-agent-path.spec.ts',
  'image-prompts-preflight.spec.ts',
  'image-prompts-route-instruction.spec.ts',
  'image-prompts-ui-logic.spec.ts',
  'image-prompts-validation.spec.ts',
  'image-stale.spec.ts',
  'ledger.spec.ts',
  'messages-idempotency.spec.ts',
  'operation-policy.spec.ts',
  'pricing.spec.ts',
  'project-read-errors.spec.ts',
  'provider-block.spec.ts',
  'quote.spec.ts',
  'rls-isolation.spec.ts',
  'service-role-client.spec.ts',
  'shot-element-binding.spec.ts',
  'shot-generation-prompt.spec.ts',
  'shot-generation.spec.ts',
  'shot-staleness.spec.ts',
  'shot-visual-description.spec.ts',
  'smoke-guard.spec.ts',
  'shot-voiceover.spec.ts',
  'shots-generation-state-machine.spec.ts',
  'shots-validation.spec.ts',
  'route-max-duration.spec.ts',
  'spec-layers.spec.ts',
  'storyboard-advance.spec.ts',
  'video-prompts-advance.spec.ts',
  'storyboard-config.spec.ts',
  'storyboard-film-logic.spec.ts',
  'storyboard-images-route.spec.ts',
  'storyboard-images.spec.ts',
  'storyboard-motion-logic.spec.ts',
  'storyboard-music-logic.spec.ts',
  'storyboard-music.spec.ts',
  'storyboard-timeline-logic.spec.ts',
  'storyboard-voiceover-logic.spec.ts',
  'storyboard-voiceover.spec.ts',
  'tool-schema-keywords.spec.ts',
  'turn-credits-route.spec.ts',
  'usage-module.spec.ts',
  'video-models.spec.ts',
  'wiring-identity.spec.ts',
] as const
