import type { createClient } from '@/lib/supabase/server'
import { ELEMENT_TYPES, type ElementType } from '@/lib/config/enums'
import { isUniqueViolation } from '@/lib/shot-key'
import type { ProjectElement } from '@/lib/elements/read'

type SupabaseServerClient = Awaited<ReturnType<typeof createClient>>

const SHORT_LABEL_MAX_LENGTH = 60

// Distinct from SHOT_ELEMENT_TYPES (which is about shot-bindability, not creatability)
// even though the value set is identical today - the two rules could diverge, so they get
// their own name rather than reusing enums.ts's derived subset for a purpose it wasn't
// named for. A style element is generated by the pipeline, never user-created, and there
// is exactly one per project - this is the one place that invariant is guarded.
const CREATABLE_ELEMENT_TYPES = ELEMENT_TYPES.filter(
  (t): t is Exclude<ElementType, 'style'> => t !== 'style'
)

export type BoundShot = { shot_id: string; shot_number: number; label: string }

export type ElementCreateResult =
  | { success: true; element: ProjectElement }
  | { success: false; error: string; reason?: 'collision'; conflictingType?: ElementType }

export type ElementNameSaveResult =
  | { success: true; unchanged?: true }
  | { success: false; error: string; reason?: 'collision'; conflictingType?: ElementType }

export type ElementDescriptionSaveResult =
  | { success: true; unchanged?: true }
  | { success: false; error: string }

export type ElementDeleteResult =
  | { success: true }
  | { success: false; error: string; reason?: 'style' | 'bound'; boundShots?: BoundShot[] }

type OwnedElement = {
  id: string
  project_id: string
  name: string
  description: string | null
  type: ElementType
  reference_image_path: string | null
}

// Not found and wrong-owner collapse to the same null, same reasoning as loadOwnedShot in
// workbench/actions.ts: RLS is the backstop, not the only check, since these functions are
// called directly (with an explicit userId) by tests against an RLS-bypassing client.
// Exported so src/lib/elements/reference.ts can reuse the same ownership join rather than
// duplicating it.
export async function loadOwnedElement(
  supabase: SupabaseServerClient,
  elementId: string,
  userId: string
): Promise<OwnedElement | null> {
  const { data } = await supabase
    .from('elements')
    .select('id, project_id, name, description, type, reference_image_path, projects!inner(user_id)')
    .eq('id', elementId)
    .eq('projects.user_id', userId)
    .is('deleted_at', null)
    .maybeSingle()

  if (!data) return null
  return {
    id: data.id,
    project_id: data.project_id,
    name: data.name,
    description: data.description,
    type: data.type as ElementType,
    reference_image_path: data.reference_image_path,
  }
}

async function lookupConflictingType(
  supabase: SupabaseServerClient,
  projectId: string,
  name: string
): Promise<ElementType | undefined> {
  const { data } = await supabase
    .from('elements')
    .select('type')
    .eq('project_id', projectId)
    .is('deleted_at', null)
    .ilike('name', name)
    .maybeSingle()

  return data?.type as ElementType | undefined
}

function collisionMessage(name: string, conflictingType: ElementType | undefined): string {
  const typeLabel = conflictingType ?? 'element'
  return `A ${typeLabel} named "${name}" already exists.`
}

function shortLabel(visualDescription: string | null): string {
  const trimmed = (visualDescription ?? '').trim()
  if (!trimmed) return '(no description)'
  return trimmed.length > SHORT_LABEL_MAX_LENGTH
    ? `${trimmed.slice(0, SHORT_LABEL_MAX_LENGTH)}…`
    : trimmed
}

// Covers both plain shot_elements bindings and shot_dialogue speakers in one check - a
// dialogue line's element_id is a non-null FK, so a speaking character is always bound and
// needs no separate check (see CLAUDE.md's delete-is-blocked-while-bound rule).
async function findBoundShots(supabase: SupabaseServerClient, elementId: string): Promise<BoundShot[]> {
  const [{ data: viaElements }, { data: viaDialogue }] = await Promise.all([
    supabase.from('shot_elements').select('shot_id').eq('element_id', elementId),
    supabase.from('shot_dialogue').select('shot_id').eq('element_id', elementId),
  ])

  const shotIds = Array.from(
    new Set([...(viaElements ?? []), ...(viaDialogue ?? [])].map((row) => row.shot_id))
  )
  if (shotIds.length === 0) return []

  const { data: shots } = await supabase
    .from('shots')
    .select('id, order_index, visual_description')
    .in('id', shotIds)

  return (shots ?? [])
    .slice()
    .sort((a, b) => a.order_index - b.order_index)
    .map((shot) => ({
      shot_id: shot.id,
      shot_number: shot.order_index + 1,
      label: shortLabel(shot.visual_description),
    }))
}

export async function createElementForUser(
  supabase: SupabaseServerClient,
  projectId: string,
  name: string,
  description: string | null,
  type: ElementType,
  userId: string
): Promise<ElementCreateResult> {
  const trimmedName = name.trim()
  if (!trimmedName) return { success: false, error: 'Name is required' }
  if (!(CREATABLE_ELEMENT_TYPES as readonly ElementType[]).includes(type)) {
    return { success: false, error: 'Invalid element type' }
  }

  const { data: project } = await supabase
    .from('projects')
    .select('id')
    .eq('id', projectId)
    .eq('user_id', userId)
    .maybeSingle()
  if (!project) return { success: false, error: 'Project not found' }

  const trimmedDescription = description?.trim() || null

  const { data, error } = await supabase
    .from('elements')
    .insert({ project_id: projectId, name: trimmedName, description: trimmedDescription, type })
    .select('id, name, description, type, reference_image_path')
    .single()

  if (error) {
    if (isUniqueViolation(error)) {
      const conflictingType = await lookupConflictingType(supabase, projectId, trimmedName)
      return {
        success: false,
        error: collisionMessage(trimmedName, conflictingType),
        reason: 'collision',
        conflictingType,
      }
    }
    return { success: false, error: error.message }
  }

  return {
    success: true,
    element: {
      id: data.id,
      name: data.name,
      description: data.description,
      type: data.type as ElementType,
      reference_image_path: data.reference_image_path,
      reference_image_url: null,
    },
  }
}

export async function updateElementNameForUser(
  supabase: SupabaseServerClient,
  elementId: string,
  name: string,
  userId: string
): Promise<ElementNameSaveResult> {
  const element = await loadOwnedElement(supabase, elementId, userId)
  if (!element) return { success: false, error: 'Element not found' }

  const trimmed = name.trim()
  if (!trimmed) return { success: false, error: 'Name is required' }
  if (trimmed === element.name) return { success: true, unchanged: true }

  const { error } = await supabase.from('elements').update({ name: trimmed }).eq('id', elementId)

  if (error) {
    if (isUniqueViolation(error)) {
      const conflictingType = await lookupConflictingType(supabase, element.project_id, trimmed)
      return {
        success: false,
        error: collisionMessage(trimmed, conflictingType),
        reason: 'collision',
        conflictingType,
      }
    }
    return { success: false, error: error.message }
  }

  return { success: true }
}

export async function updateElementDescriptionForUser(
  supabase: SupabaseServerClient,
  elementId: string,
  description: string | null,
  userId: string
): Promise<ElementDescriptionSaveResult> {
  const element = await loadOwnedElement(supabase, elementId, userId)
  if (!element) return { success: false, error: 'Element not found' }

  const trimmed = description?.trim() || null
  if (trimmed === element.description) return { success: true, unchanged: true }

  const { error } = await supabase.from('elements').update({ description: trimmed }).eq('id', elementId)
  if (error) return { success: false, error: error.message }

  return { success: true }
}

export async function deleteElementForUser(
  supabase: SupabaseServerClient,
  elementId: string,
  userId: string
): Promise<ElementDeleteResult> {
  const element = await loadOwnedElement(supabase, elementId, userId)
  if (!element) return { success: false, error: 'Element not found' }

  if (element.type === 'style') {
    return { success: false, error: 'The style element cannot be deleted', reason: 'style' }
  }

  const boundShots = await findBoundShots(supabase, elementId)
  if (boundShots.length > 0) {
    return {
      success: false,
      error: 'This element is used in one or more shots and cannot be deleted',
      reason: 'bound',
      boundShots,
    }
  }

  const { error } = await supabase
    .from('elements')
    .update({ deleted_at: new Date().toISOString() })
    .eq('id', elementId)
  if (error) return { success: false, error: error.message }

  return { success: true }
}
