-- How the current voiceover was made: generated by text-to-speech, or uploaded and
-- aligned. Null when there is no current voiceover. Mirrors VOICEOVER_SOURCES in
-- src/lib/config/enums.ts.
ALTER TABLE "public"."projects"
    ADD COLUMN "voiceover_source" text,
    ADD CONSTRAINT "projects_voiceover_source_check"
        CHECK ("voiceover_source" IS NULL OR "voiceover_source" IN ('generated', 'uploaded'));
